export const MAIN_STACK_NAVIGATION : string = "MAIN_STACK_NAVIGATION";
export const DRAWER_NAVIGATION : string = "DRAWER_NAVIGATION";
export const TAB_BOTTOM_NAVIGATION : string = "TAB_BOTTOM_NAVIGATION";